# Use the official PostgreSQL image as the base image
FROM postgres:15.1-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=mysecurepassword
ENV POSTGRES_DB=postgres
