version: '3.8'

services:
  db:
    container_name: ylab_db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    volumes:
      - pytest_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    container_name: ylab_cache
    build:
      context: .
      dockerfile: Dockerfile-cache
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
        test: [ "CMD", "redis-cli ping" ]
        interval: 10s
        timeout: 5s
        retries: 5

  web:
    build:
      context: ./server
      dockerfile: dockerfile.txt
    container_name: ylab_server
    command: python server/start.py
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgres:mysecurepassword@db/postgres
      - TEST_CHECK=YES_I_WANT_TO_DELETE_MY_DATA
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  pytest:
    build:
      context: ./tests
      dockerfile: dockerfile.txt
    command: pytest
    container_name: ylab_test
    depends_on:
      web:
        condition: service_healthy

volumes:
  pytest_postgres_data:
