# Use the official Redis image as the base image
FROM redis:latest

# Set a custom configuration file if needed (optional)
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Expose the default Redis port
EXPOSE 6379

# Start the Redis server
CMD ["redis-server"]
