# Use the official Python image as the base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app
ENV DATABASE_URL="postgres:mysecurepassword@db/postgres"

# Copy the application files to the working directory
COPY . /app

# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get install -y curl

EXPOSE 8000
# Command to run the application
CMD ["python", "start.py"]
